#!/usr/bin/env bash
set -euo pipefail

# cut-release.sh <version> — one-shot release.
#
#   1. bump VERSION + sync derived files (package.json, plugin.json)
#   2. regenerate CHANGELOG.md from Conventional Commits (git-cliff)
#   3. open a "release: <version>" PR, auto-merge it once required checks pass
#   4. tag the merged commit and push the tag
#
# The tag push fires .github/workflows/release.yml (npm publish + GitHub
# Release, whose notes are generated by git-cliff). `main` is a protected branch
# with required status checks, so the release commit must land via a PR — a
# direct push is rejected. Tags aren't protected, so the tag push is direct.
#
# Requires: git-cliff (brew install git-cliff | cargo install git-cliff |
#           https://github.com/orhun/git-cliff/releases) and gh authenticated
#           as the fujibee account (direnv pins GH_TOKEN for this repo).
#
# Usage: scripts/release/cut-release.sh 1.0.4

die() { echo "cut-release: $*" >&2; exit 1; }

VERSION="${1:-}"
[ -n "$VERSION" ] || die "usage: cut-release.sh <version>  (semver, no leading 'v')"
case "$VERSION" in
  v*) die "version must not start with 'v' (got '$VERSION')" ;;
  [0-9]*.[0-9]*.[0-9]*) ;;
  *) die "version must be semver MAJOR.MINOR.PATCH (got '$VERSION')" ;;
esac

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

command -v git-cliff >/dev/null 2>&1 \
  || die "git-cliff not found — install it (brew install git-cliff) and retry"
command -v gh >/dev/null 2>&1 || die "gh not found"

# Must be on a clean, up-to-date main, and authenticated as fujibee.
[ -z "$(git status --porcelain)" ] || die "working tree is not clean"
[ "$(git rev-parse --abbrev-ref HEAD)" = "main" ] || die "must be on main"
git fetch origin -q
[ "$(git rev-parse HEAD)" = "$(git rev-parse origin/main)" ] \
  || die "local main is not in sync with origin/main — pull first"
who="$(gh api user --jq .login 2>/dev/null || true)"
[ "$who" = "fujibee" ] || die "gh identity is '$who', expected 'fujibee' (check direnv .envrc)"

TAG="v$VERSION"
git rev-parse "$TAG" >/dev/null 2>&1 && die "tag $TAG already exists"
BRANCH="release/$TAG"

echo "==> Preparing $TAG on branch $BRANCH"
git switch -c "$BRANCH"

# 1. bump + sync
echo "$VERSION" > VERSION
./scripts/release/sync-version.sh

# 2. regenerate the changelog including this release's section
git-cliff --tag "$TAG" -o CHANGELOG.md

# 3. commit + push the release PR
git add VERSION package.json .claude-plugin/plugin.json CHANGELOG.md
git commit -m "release: $VERSION"
git push -u origin "$BRANCH"

echo "==> Opening release PR"
gh pr create --base main --head "$BRANCH" \
  --title "release: $VERSION" \
  --body "Automated release of \`$VERSION\`.

- VERSION bump + synced \`package.json\` / \`.claude-plugin/plugin.json\`
- CHANGELOG.md regenerated from Conventional Commits

Merging this and pushing \`$TAG\` triggers the publish pipeline (npm + GitHub Release)."

echo "==> Enabling auto-merge (squash) — waits for required checks"
gh pr merge "$BRANCH" --squash --auto --delete-branch

# 4. wait for the PR to merge, then tag the resulting main commit
echo "==> Waiting for the release PR to merge (required checks must pass)…"
for _ in $(seq 1 60); do
  state="$(gh pr view "$BRANCH" --json state --jq .state 2>/dev/null || echo UNKNOWN)"
  case "$state" in
    MERGED) break ;;
    CLOSED) die "release PR was closed without merging" ;;
  esac
  sleep 15
done
[ "${state:-}" = "MERGED" ] || die "timed out waiting for the release PR to merge; once it merges, run: git fetch origin && git tag $TAG origin/main && git push origin $TAG"

git switch main
git pull --ff-only origin main
git tag "$TAG"
git push origin "$TAG"

echo "==> Pushed $TAG. release.yml will publish to npm and cut the GitHub Release after the production approval."
